student_count = 11

puts "The students of Villiains Academy"
puts "--------"
puts "Dr. Hannibal Lecter"
puts "Darth Vader"
puts "Nurse Ratched"
puts "Michael Corleone"
puts "alex DeLarge"
puts "The Wicked Witch of the WEst"
puts "The Terminator"
puts "Freddy Krueger"
puts "The joker"
puts "Joffrey Baratheon"
puts "Norman Bates"
puts " "
puts "overall, we have #{student_count} great students"
